create view edwp.team_boxscore as 
SELECT 
        c.GameDate AS gamedate,
        c.GameID AS gameid,
        c.Home AS home,
        c.Visitor AS visitor,
        home.hPlayerRotation AS hPlayerRotation,
        home.hMIN AS hMIN,
        home.hFGM AS hFGM,
        home.hFGA AS hFGA,
        home.hP3M AS hP3M,
        home.hP3A AS hP3A,
        home.hFTM AS hFTM,
        home.hFTA AS hFTA,
        home.hOREB AS hOREB,
        home.hDREB AS hDREB,
        home.hREB AS hREB,
        home.hAST AS hAST,
        home.hSTL AS hSTL,
        home.hBLK AS hBLK,
        home.hTOV AS hTOV,
        home.hPF AS hPF,
        home.hPTS AS hPTS,
        home.hGameScore AS hGameScore,
        home.hPlusMinus AS hPlusMinus,
        visitor.vPlayerRotation AS vPlayerRotation,
        visitor.vMIN AS vMIN,
        visitor.vFGM AS vFGM,
        visitor.vFGA AS vFGA,
        visitor.vP3M AS vP3M,
        visitor.vP3A AS vP3A,
        visitor.vFTM AS vFTM,
        visitor.vFTA AS vFTA,
        visitor.vOREB AS vOREB,
        visitor.vDREB AS vDREB,
        visitor.vREB AS vREB,
        visitor.vAST AS vAST,
        visitor.vSTL AS vSTL,
        visitor.vBLK AS vBLK,
        visitor.vTOV AS vTOV,
        visitor.vPF AS vPF,
        visitor.vPTS AS vPTS,
        visitor.vGameScore AS vGameScore,
        visitor.vPlusMinus AS vPlusMinus
    FROM
        ((edwp.d_calendar c
        JOIN (SELECT 
            edwp.f_stats.TEAMID AS TEAMID,
                edwp.f_stats.GameID AS GameID,
                COUNT(edwp.f_stats.TEAMID) AS hPlayerRotation,
                SUM(edwp.f_stats.MIN) AS hMIN,
                SUM(edwp.f_stats.FGM) AS hFGM,
                SUM(edwp.f_stats.FGA) AS hFGA,
                SUM(edwp.f_stats.P3M) AS hP3M,
                SUM(edwp.f_stats.P3A) AS hP3A,
                SUM(edwp.f_stats.FTM) AS hFTM,
                SUM(edwp.f_stats.FTA) AS hFTA,
                SUM(edwp.f_stats.OREB) AS hOREB,
                SUM(edwp.f_stats.DREB) AS hDREB,
                SUM(edwp.f_stats.DREB+edwp.f_stats.OREB) AS hREB,
                SUM(edwp.f_stats.AST) AS hAST,
                SUM(edwp.f_stats.STL) AS hSTL,
                SUM(edwp.f_stats.BLK) AS hBLK,
                SUM(edwp.f_stats.TOV) AS hTOV,
                SUM(edwp.f_stats.Fouls) AS hPF,
                SUM(edwp.f_stats.PTS) AS hPTS,
                SUM(edwp.f_stats.GameScore) AS hGameScore,
                SUM(edwp.f_stats.PlusMinus) AS hPlusMinus
        FROM
            edwp.f_stats
        GROUP BY edwp.f_stats.TEAMID , edwp.f_stats.GameID) home ON (((home.GameID = c.GameID)
            AND (home.TEAMID = c.Home))))
        JOIN (SELECT 
            edwp.f_stats.TEAMID AS TEAMID,
                edwp.f_stats.GameID AS GameID,
                COUNT(edwp.f_stats.TEAMID) AS vPlayerRotation,
                SUM(edwp.f_stats.MIN) AS vMIN,
                SUM(edwp.f_stats.FGM) AS vFGM,
                SUM(edwp.f_stats.FGA) AS vFGA,
                SUM(edwp.f_stats.P3M) AS vP3M,
                SUM(edwp.f_stats.P3A) AS vP3A,
                SUM(edwp.f_stats.FTM) AS vFTM,
                SUM(edwp.f_stats.FTA) AS vFTA,
                SUM(edwp.f_stats.OREB) AS vOREB,
                SUM(edwp.f_stats.DREB) AS vDREB,
                SUM(edwp.f_stats.DREB+edwp.f_stats.OREB) AS vREB,
                SUM(edwp.f_stats.AST) AS vAST,
                SUM(edwp.f_stats.STL) AS vSTL,
                SUM(edwp.f_stats.BLK) AS vBLK,
                SUM(edwp.f_stats.TOV) AS vTOV,
                SUM(edwp.f_stats.Fouls) AS vPF,
                SUM(edwp.f_stats.PTS) AS vPTS,
                SUM(edwp.f_stats.GameScore) AS vGameScore,
                SUM(edwp.f_stats.PlusMinus) AS vPlusMinus
        FROM
            edwp.f_stats
        GROUP BY edwp.f_stats.TEAMID , edwp.f_stats.GameID) visitor ON (((c.GameID = visitor.GameID)
            AND (c.Visitor = visitor.TEAMID))))
		order by c.gamedate desc;